@file:Suppress("unused")
package relaxeddd.englishnotify.common

const val CHECKED_ITEM = "checked_item"
const val CHECKED_ITEMS = "checked_items"
const val ITEMS = "items"
const val WORDS = "words"
const val USERS = "users"

const val ENG = "eng"
const val RUS = "rus"
const val V2 = "v2"
const val V3 = "v3"
const val TRANSCRIPTION = "transcription"
const val TAG = "tag"
const val TAGS = "tags"
const val SAMPLES = "samples"
const val SAMPLE_RUS = "sampleRus"
const val SAMPLE_ENG = "sampleEng"
const val IS_CREATED_BY_USER = "isCreatedByUser"
const val IS_OWN_CATEGORY = "isOwnCategory"
const val IS_DELETED = "isDeleted"
const val LEARN_STAGE = "learnStage"
const val LEARN_STAGE_0 = "learnStage0"
const val LEARN_STAGE_1 = "learnStage1"
const val LEARN_STAGE_2 = "learnStage2"
const val LEARN_STAGE_3 = "learnStage3"

const val ID = "id"
const val EMAIL = "email"
const val RECEIVE_NOTIFICATIONS = "receiveNotifications"
const val NOTIFICATIONS_TIME_TYPE = "notificationsTimeType"
const val TAGS_AVAILABLE = "tagsAvailable"
const val TAGS_SELECTED = "tagsSelected"
const val LEARN_LANGUAGE_TYPE = "learnLanguageType"

const val EXERCISE = "exercise"

const val START_HOUR = "startHour"
const val DURATION_HOURS = "durationHours"

const val ERROR_TOKEN_NOT_INIT = "User token not init"
const val ERROR_NOT_AUTHORIZED = "User not authorized"
const val ERROR_USER_NOT_FOUND = "User not found"
const val ERROR_APP_INFO = "App info not found"
const val ERROR_SEND_TEST_NOTIFICATION = "Error send test notification"
const val ERROR_FIREBASE_NETWORK = "Firebase Network exception"

const val APP = "app"
const val CATEGORY = "category"
const val CONTENT = "content"
const val NAME = "name"
const val VALUE = "value"
const val TIMESTAMP = "timestamp"
const val TYPE = "type"
const val TITLE = "title"
const val TEXT = "text"
const val WORD_LEARN_STAGE = "wordLearnStage"
const val HIDE_OFF_NOTIFICATIONS_WARNING = "hideOffNotificationsWarning"
const val IS_SHOW_OWN_WORDS = "isShowOwnWords"
const val SYSTEM = "system"
const val OWN_WORD = "ownWord"
const val PUSH = "push"
const val SELECTED_TAGS = "selectedTags"
const val LEVEL = "level"
const val USER_EMAIL = "userEmail"
const val COUNT = "count"
const val TRAINING_TYPE = "trainingType"
const val VOTE_RECEIVE_NOTIFICATIONS = "voteReceiveNotifications"

const val OWN_KEY_SYMBOL = "!"

