package relaxeddd.englishnotify.common

const val EMPTY_RES = -1

const val TRAINING_ENG_TO_RUS = 0
const val TRAINING_RUS_TO_ENG = 1
const val TRAINING_MIXED = 2

const val NOTIFICATIONS_VIEW_WITH_TRANSLATE = 0
const val NOTIFICATIONS_VIEW_WITH_QUESTION = 1

// TODO: refactor to enum
const val NAVIGATION_EXIT = 999
const val NAVIGATION_DIALOG_REPEAT = 1000
const val NAVIGATION_DIALOG_CHECK_TAGS = 1001
const val NAVIGATION_DIALOG_SORTED_BY = 1002
const val NAVIGATION_FRAGMENT_NOTIFICATIONS = 1003
const val NAVIGATION_FRAGMENT_SETTINGS = 1004
const val NAVIGATION_DIALOG_LEARN_ENGLISH = 1005
const val NAVIGATION_DIALOG_APP_ABOUT = 1006
const val NAVIGATION_DIALOG_PRIVACY_POLICY = 1007
const val NAVIGATION_GOOGLE_AUTH = 1008
const val NAVIGATION_DIALOG_SEND_FEEDBACK = 1009
const val NAVIGATION_GOOGLE_LOGOUT = 1010
const val NAVIGATION_DIALOG_CONFIRM_LOGOUT = 1011
const val NAVIGATION_WEB_PLAY_MARKET = 1012
const val NAVIGATION_DIALOG_RATE_APP = 1020
const val NAVIGATION_DIALOG_NOTIFICATIONS_VIEW = 1030
const val NAVIGATION_DIALOG_NEW_VERSION = 1040
const val NAVIGATION_DIALOG_PATCH_NOTES = 1050
const val NAVIGATION_DIALOG_NIGHT_TIME = 1060
const val NAVIGATION_DIALOG_TEST_NOTIFICATIONS = 1070
const val NAVIGATION_INIT_BILLING = 1080
const val NAVIGATION_DIALOG_OWN_CATEGORY = 1091
const val NAVIGATION_FRAGMENT_TRAINING = 1111
const val NAVIGATION_DIALOG_INFO_TRAINING = 1121
const val NAVIGATION_DIALOG_CHANGE_ACCOUNT = 1131
const val NAVIGATION_DIALOG_CONFIRM_DISABLE_NOTIFICATIONS = 1181
const val NAVIGATION_FRAGMENT_SELECT_CATEGORY = 1191
const val NAVIGATION_FRAGMENT_STATISTIC = 1201
const val NAVIGATION_FRAGMENT_TIME = 1211
const val NAVIGATION_ACTION_HIDE_FILTER = 1221
const val NAVIGATION_PLAY_WORD = 1271
const val NAVIGATION_DIALOG_THEME = 1291
const val NAVIGATION_HIDE_KEYBOARD = 1301
const val NAVIGATION_DIALOG_RECEIVE_HELP = 1311
const val NAVIGATION_DIALOG_VOTE_RECEIVE_NOTIFICATIONS = 1321
const val NAVIGATION_DIALOG_LIKE_APP = 1332
const val NAVIGATION_FRAGMENT_WORD = 1340
const val NAVIGATION_WORD_EXISTS_ERROR = 1345
const val NAVIGATION_ANIMATE_RESULT = 1346
const val NAVIGATION_ANIMATE_LEARNED_COUNT = 1347
const val NAVIGATION_PLAY_WORD_DEPENDS_ON_TRANSLATION = 1348
const val NAVIGATION_RECREATE_ACTIVITY = 1349
const val NAVIGATION_SHOW_KEYBOARD = 1350
const val NAVIGATION_WORD_EXISTS_DIALOG = 1351
const val NAVIGATION_ANIMATE_LEARNED_COUNT_MINUS = 1352
const val NAVIGATION_DIALOG_SECONDARY_PROGRESS_INFO = 1353
const val NAVIGATION_DIALOG_SWAP_PROGRESS = 1354
const val NAVIGATION_DIALOG_CHECK_SAVE_WORDS = 1356
const val NAVIGATION_DIALOG_CHECK_LOAD_WORDS = 1357
const val NAVIGATION_DIALOG_TRUE_ANSWERS_TO_LEARN = 1358
const val NAVIGATION_DIALOG_NOTIFICATION_LEARN_POINTS = 1359
const val NAVIGATION_FRAGMENT_PARSE = 1360
const val NAVIGATION_FRAGMENT_PARSED_WORDS = 1361

const val NAVIGATION_LOADING_SHOW = 801
const val NAVIGATION_LOADING_HIDE = 802
const val NAVIGATION_ACTIVITY_BACK = 790
const val NAVIGATION_GLOBAL_DICTIONARY = 780
const val NAVIGATION_ACTIVITY_BACK_TWICE = 770

const val SELECTED_ITEM = "selected_item"
