name: UI tests

on:
  pull_request:
    branches: [ "master" ]

jobs:
  ui_tests:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: UI Tests
      id: testing
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        script: ./gradlew connectedCheck
      continue-on-error: true

