name: Unit tests

on:
  pull_request:
    branches: [ "dev" ]

jobs:
  unit_tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Unit tests
      run: ./gradlew test
      continue-on-error: true

    - name: Make unit tests report
      uses: asadmansr/android-test-report-action@v1.2.0
      if: ${{ always() }}


